spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}/whosbook?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENTID}
            clientSecret: ${GOOGLE_SECRET}
            scope: email, profile
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 300
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: admin@email.com

