export const {
  VITE_SERVER_URL,
  VITE_KAKAO_API_KEY,
  VITE_OAUTH_CLIENT_ID,
  VITE_OAUTH_CLIENT_PW,
  VITE_OAUTH_GOOGLE_REDIRECT_URL,
  VITE_OAUTH2_GOOGLE_ENDPOINT,
  VITE_NGROK_SERVER_URL,
} = import.meta.env;
